//baseURL 및 기타 상수
import { type Cafe } from "./Types";

export const baseURL = "http://localhost:8080";

export const waffleCafe: Cafe = {
  name: "와플카페",
  url: "https://cafe.naver.com/wafflecafe",
  manager: "매니저",
  createdAt: "2024.01.13 개설",
  location: "서울특별시 관악구",
  description: "와플스튜디오 team7의 토이프로젝트 카페입니다.",
};

export const itemsPerPage = 10;

//테스트용

export const aList = [
  {
    title: "첫번째 글입니다~~",
    id: 1,
    board: "자유게시판",
    comment: 10,
    author: "허유민",
    date: "2024.01.12.",
    viewCnt: 33,
    like: 3,
  },
  {
    title: "두번째 글입니다~~",
    id: 2,
    board: "자유게시판",
    comment: 1,
    author: "허유민",
    date: "2024.01.13.",
    viewCnt: 1,
    like: 2,
  },
  {
    title: "세번째 게시글 입니다.",
    id: 3,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "네번째 게시글",
    id: 4,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "다섯번째 게시글",
    id: 5,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "6 게시글",
    id: 6,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "7 게시글",
    id: 7,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "8 게시글",
    id: 8,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "9 게시글",
    id: 9,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "10 게시글",
    id: 10,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "11 게시글",
    id: 11,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "12 게시글",
    id: 12,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "13 게시글",
    id: 13,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "14 게시글",
    id: 14,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
  {
    title: "15 게시글",
    id: 15,
    board: "자유게시판",
    comment: 5,
    author: "허유민",
    date: "2024.01.14.",
    viewCnt: 33,
    like: 100,
  },
];
